import type { Detection } from './detect.ts';
import { runtimeUser } from './dockerfile.ts';

export interface ChartOptions {
  /** Image repository without a tag, e.g. ghcr.io/acme/payments-api. */
  image: string;
  /** Whether the Dockerfile is ours, so its numeric user is known. */
  generatedDockerfile: boolean;
}

const isJava = (d: Detection) => d.stack === 'spring-maven' || d.stack === 'spring-gradle';

/** A Helm chart: deployment, service, probes, resources, and a restricted security context. */
export function helmChart(d: Detection, opts: ChartOptions): Record<string, string> {
  const n = d.name;
  const resources = isJava(d)
    ? { cpu: '250m', memory: '512Mi', limit: '1Gi' }
    : { cpu: '100m', memory: '128Mi', limit: '256Mi' };
  const probe = d.healthPath
    ? `  httpGet:\n    path: ${d.healthPath}\n    port: http`
    : '  tcpSocket:\n    port: http';
  const runAsUser = opts.generatedDockerfile ? `\n  runAsUser: ${String(runtimeUser(d))}` : '';

  const values = `# Generated by Kodra AI Agent.
replicaCount: 1

image:
  repository: ${opts.image}
  # Defaults to the chart's appVersion. CI tags images with the commit SHA: set it on deploy.
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []

containerPort: ${String(d.port)}

service:
  type: ClusterIP
  port: 80

# Requests sized for a small service; tune them from real usage. No CPU limit, to avoid throttling.
resources:
  requests:
    cpu: ${resources.cpu}
    memory: ${resources.memory}
  limits:
    memory: ${resources.limit}

startupProbe:
${probe}
  periodSeconds: 5
  failureThreshold: 30

livenessProbe:
${probe}
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
${probe}
  periodSeconds: 5
  failureThreshold: 3

podSecurityContext:
  runAsNonRoot: true${runAsUser}
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: [ALL]

env: []

nodeSelector: {}
tolerations: []
affinity: {}
`;

  const helpers = `{{/* Generated by Kodra AI Agent. */}}
{{- define "${n}.fullname" -}}
{{- if contains .Chart.Name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}

{{- define "${n}.selectorLabels" -}}
app.kubernetes.io/name: {{ .Chart.Name }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}

{{- define "${n}.labels" -}}
helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" }}
{{ include "${n}.selectorLabels" . }}
app.kubernetes.io/version: {{ .Values.image.tag | default .Chart.AppVersion | quote }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}
`;

  const deployment = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "${n}.fullname" . }}
  labels:
    {{- include "${n}.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "${n}.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "${n}.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        # The root filesystem is read-only; /tmp is the one writable folder.
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
`;

  const service = `apiVersion: v1
kind: Service
metadata:
  name: {{ include "${n}.fullname" . }}
  labels:
    {{- include "${n}.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "${n}.selectorLabels" . | nindent 4 }}
`;

  const dir = `charts/${n}`;
  return {
    [`${dir}/Chart.yaml`]: `apiVersion: v2
name: ${n}
description: Helm chart for ${n}, generated by Kodra AI Agent.
type: application
version: 0.1.0
appVersion: "0.1.0"
`,
    [`${dir}/values.yaml`]: values,
    [`${dir}/.helmignore`]: '.DS_Store\n.git/\n*.swp\n*.bak\n*.tmp\n',
    [`${dir}/templates/_helpers.tpl`]: helpers,
    [`${dir}/templates/deployment.yaml`]: deployment,
    [`${dir}/templates/service.yaml`]: service,
  };
}
