import { CHECKOUT_ACTION, HELM, IMAGES } from './images.ts';

export interface CiOptions {
  /** Image repository without a tag. */
  image: string;
  chartDir: string;
  /** The branch whose pushes publish the image. */
  defaultBranch: string;
}

/**
 * GitHub Actions: builds the image on every PR and push, pushes it to GHCR only on the
 * default branch, and lints and renders the chart. Actions and Helm are pinned.
 */
export function githubWorkflow(o: CiOptions): string {
  return `# Generated by Kodra AI Agent.
name: Container

on:
  pull_request:
  push:
    branches: [${JSON.stringify(o.defaultBranch)}]

permissions:
  contents: read

jobs:
  image:
    name: Build the image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE: ${o.image}
    steps:
      - uses: ${CHECKOUT_ACTION}
      - name: Build
        run: docker build -t "$IMAGE:$GITHUB_SHA" .
      - name: Push to GitHub Container Registry
        if: github.event_name == 'push'
        env:
          REGISTRY_TOKEN: \${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$REGISTRY_TOKEN" | docker login ghcr.io -u "$GITHUB_ACTOR" --password-stdin
          docker push "$IMAGE:$GITHUB_SHA"

  chart:
    name: Lint the Helm chart
    runs-on: ubuntu-latest
    env:
      HELM_VERSION: ${HELM.version}
      HELM_SHA256: ${HELM.linuxAmd64Sha256}
    steps:
      - uses: ${CHECKOUT_ACTION}
      - name: Install Helm (checksum-verified)
        run: |
          archive="helm-\${HELM_VERSION}-linux-amd64.tar.gz"
          curl -sSfL -o "$archive" "https://get.helm.sh/\${archive}"
          echo "\${HELM_SHA256}  \${archive}" | sha256sum --check
          tar -xzf "$archive" linux-amd64/helm
          sudo mv linux-amd64/helm /usr/local/bin/helm
      - run: helm lint ${o.chartDir}
      - run: helm template ci ${o.chartDir} > /dev/null
`;
}

/**
 * GitLab CI: builds the image with Docker-in-Docker, pushes it to the project's registry
 * only on the default branch, and lints and renders the chart.
 */
export function gitlabCi(o: CiOptions): string {
  return `# Generated by Kodra AI Agent.
stages: [build, package]

image-build:
  stage: build
  image: ${IMAGES.dockerCli}
  services:
    - ${IMAGES.dockerDind}
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" .
    - |
      if [ "$CI_COMMIT_BRANCH" = "$CI_DEFAULT_BRANCH" ]; then
        echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
        docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
      fi

chart-lint:
  stage: package
  image:
    name: ${IMAGES.helm}
    entrypoint: [""]
  script:
    - helm lint ${o.chartDir}
    - helm template ci ${o.chartDir} > /dev/null
`;
}
