import type { Detection } from './detect.ts';
import { IMAGES } from './images.ts';

/** The non-root user each runtime image runs as. Numeric, so Kubernetes can verify it. */
export function runtimeUser(detection: Detection): number {
  switch (detection.stack) {
    case 'node':
      return 1000; // the node image's own `node` user
    case 'go':
      return 65532; // distroless `nonroot`
    default:
      return 10001;
  }
}

const HEADER = '# Generated by Kodra AI Agent: multi-stage, pinned base images, non-root user.';
const json = (args: readonly string[]) => JSON.stringify(args).replaceAll('","', '", "');

/** A multi-stage Dockerfile for the detected stack. */
export function dockerfile(d: Detection): string {
  const port = String(d.port);
  switch (d.stack) {
    case 'spring-maven':
    case 'spring-gradle': {
      const java = d.java?.version ?? 21;
      const build =
        d.stack === 'spring-maven'
          ? [
              `FROM ${IMAGES.maven[java]} AS build`,
              'WORKDIR /src',
              'COPY . .',
              "RUN mvn -B -q package -DskipTests \\\n && find target -maxdepth 1 -name '*.jar' ! -name '*-plain.jar' -exec cp {} /app.jar \\;",
            ]
          : [
              `FROM ${IMAGES.gradle[java]} AS build`,
              'WORKDIR /src',
              'COPY . .',
              "RUN gradle bootJar --no-daemon -q -x test \\\n && find build/libs -maxdepth 1 -name '*.jar' ! -name '*-plain.jar' -exec cp {} /app.jar \\;",
            ];
      return [
        HEADER,
        ...build,
        '',
        `FROM ${IMAGES.jre[java]}`,
        'RUN addgroup -S -g 10001 app && adduser -S -D -H -u 10001 -G app app',
        'WORKDIR /app',
        'COPY --from=build /app.jar /app/app.jar',
        'USER 10001',
        `EXPOSE ${port}`,
        'ENTRYPOINT ["java", "-XX:MaxRAMPercentage=75", "-jar", "/app/app.jar"]',
        '',
      ].join('\n');
    }
    case 'node': {
      const node = d.node ?? { install: 'ci', build: false, start: ['npm', 'start'] };
      const install = node.install === 'ci' ? 'npm ci' : 'npm install';
      const steps = node.build
        ? [`RUN ${install}`, 'COPY . .', 'RUN npm run build && npm prune --omit=dev']
        : [`RUN ${install} --omit=dev`, 'COPY . .'];
      return [
        HEADER,
        `FROM ${IMAGES.node} AS build`,
        'WORKDIR /app',
        'COPY package*.json ./',
        ...steps,
        '',
        `FROM ${IMAGES.node}`,
        // npm writes a cache and logs; keep them in /tmp so the root filesystem can be read-only.
        'ENV NODE_ENV=production npm_config_cache=/tmp/.npm',
        'WORKDIR /app',
        'COPY --from=build /app /app',
        'USER 1000',
        `EXPOSE ${port}`,
        `CMD ${json(node.start)}`,
        '',
      ].join('\n');
    }
    case 'python':
      return [
        HEADER,
        `FROM ${IMAGES.python} AS build`,
        'RUN python -m venv /venv',
        'ENV PATH=/venv/bin:$PATH',
        'COPY requirements.txt /tmp/requirements.txt',
        'RUN pip install --no-cache-dir -r /tmp/requirements.txt',
        '',
        `FROM ${IMAGES.python}`,
        'ENV PATH=/venv/bin:$PATH PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1',
        'RUN useradd --system --uid 10001 --no-create-home app',
        'WORKDIR /app',
        'COPY --from=build /venv /venv',
        'COPY . .',
        'USER 10001',
        `EXPOSE ${port}`,
        `CMD ${json(d.python?.cmd ?? ['python', 'main.py'])}`,
        '',
      ].join('\n');
    case 'go':
      return [
        HEADER,
        `FROM ${IMAGES.golang} AS build`,
        'WORKDIR /src',
        'COPY go.* ./',
        'RUN go mod download',
        'COPY . .',
        `RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /out/app ${d.go?.pkg ?? '.'}`,
        '',
        `FROM ${IMAGES.distroless}`,
        'COPY --from=build /out/app /app',
        'USER 65532:65532',
        `EXPOSE ${port}`,
        'ENTRYPOINT ["/app"]',
        '',
      ].join('\n');
  }
}

/** Keeps build output, dependencies, secrets, and repo metadata out of the build context. */
export function dockerignore(): string {
  return [
    '# Generated by Kodra AI Agent',
    '.git',
    '**/node_modules',
    'target',
    'build',
    '.gradle',
    '**/__pycache__',
    '*.pyc',
    '.venv',
    '.env',
    '.env.*',
    'charts',
    '.github',
    '.gitlab-ci.yml',
    '',
  ].join('\n');
}

export interface DockerfileProblem {
  line: number;
  problem: string;
}

/**
 * Checks the rules every Dockerfile from the agent must keep, including one the model
 * rewrote: each base image pinned to a tag or digest (not `latest`), and a final non-root USER.
 */
export function checkDockerfile(text: string): DockerfileProblem[] {
  const problems: DockerfileProblem[] = [];
  const stages = new Set<string>();
  let froms = 0;
  let lastUser: { line: number; value: string } | null = null;
  const lines = text.replace(/\\\r?\n/g, ' ').split(/\r?\n/);
  lines.forEach((raw, i) => {
    const line = raw.trim();
    const from = /^FROM\s+(?:--platform=\S+\s+)?(\S+)(?:\s+AS\s+(\S+))?/i.exec(line);
    if (from?.[1]) {
      froms++;
      lastUser = null;
      const image = from[1];
      if (from[2]) stages.add(from[2].toLowerCase());
      if (stages.has(image.toLowerCase()) && image.toLowerCase() !== from[2]?.toLowerCase()) return;
      const tag = /^(?:[^/]+\/)*[^:@/]+(?::([^@]+))?(?:@sha256:[a-f0-9]{64})?$/.exec(image);
      if (!image.includes('@sha256:') && (!tag?.[1] || tag[1] === 'latest')) {
        problems.push({ line: i + 1, problem: `base image ${image} is not pinned to a version` });
      }
      return;
    }
    const user = /^USER\s+(\S+)/i.exec(line);
    if (user?.[1]) lastUser = { line: i + 1, value: user[1] };
  });
  if (froms === 0) problems.push({ line: 1, problem: 'there is no FROM line' });
  const finalUser = lastUser as { line: number; value: string } | null;
  if (!finalUser) {
    problems.push({
      line: lines.length,
      problem: 'the final stage has no USER, so it runs as root',
    });
  } else if (/^(root|0)(:|$)/.test(finalUser.value)) {
    problems.push({ line: finalUser.line, problem: 'the final stage runs as root' });
  }
  return problems;
}
