import { dependencyIssues, getModelProvider, parseAgentConfig } from '@kodra-agent/connectors';
import {
  DEFAULT_AUDIT_PATH,
  formatSecretRef,
  isSecretRequired,
  SCHEMA_API_VERSION,
  type ConfigField,
  type LocalizedText,
  type Manifest,
  type SecretSpec,
} from '@kodra-agent/schema';
import { stringify } from 'yaml';
import { enabledConnectors, splitList, type AgentDraft } from './draft.ts';

export type StepId = 'start' | 'model' | 'connectors' | 'review';

/** A problem with the draft, keyed to the UI field it belongs to. The UI localizes `code`. */
export type DraftIssue = { field: string; step: StepId } & (
  | { code: 'required' }
  | { code: 'url' }
  | { code: 'pattern'; hint?: LocalizedText | undefined }
  | { code: 'integer-range'; min: number; max: number }
  | { code: 'name-format' }
  | { code: 'approver-format'; value: string }
  | { code: 'dependency'; message: LocalizedText }
  | { code: 'coming-soon' }
  | { code: 'schema'; message: string }
);

const NAME = /^[a-z0-9]([-a-z0-9]{0,51}[a-z0-9])?$/;
const APPROVER = /^(@[A-Za-z0-9][A-Za-z0-9._-]{0,79}|[UW][A-Z0-9]{2,})$/;

/** The reference written into kodra-agent.yaml for a secret. */
export function secretRefFor(secret: SecretSpec): string {
  return secret.defaultRef === 'file'
    ? formatSecretRef({ scheme: 'file', path: secret.defaultFilePath ?? `/secrets/${secret.key}` })
    : formatSecretRef({ scheme: 'env', name: secret.envVar });
}

/** Secrets an enabled connector or the model will ask for. */
/** Secrets the config names: required ones (for this target), plus the optional ones chosen. */
export function includedSecrets(
  manifest: Manifest,
  optionalChosen: readonly string[],
  target: 'compose' | 'kubernetes',
): SecretSpec[] {
  return manifest.secrets.filter(
    (s) => isSecretRequired(s, target) || optionalChosen.includes(s.key),
  );
}

function fieldValue(field: ConfigField, raw: string | undefined): unknown {
  const value = (raw ?? '').trim();
  if (value === '') return undefined;
  switch (field.kind) {
    case 'string-list':
      return splitList(value);
    case 'integer':
      return /^-?\d+$/.test(value) ? Number(value) : value;
    default:
      return value;
  }
}

function fieldsObject(fields: readonly ConfigField[], raw: Record<string, string>) {
  const out: Record<string, unknown> = {};
  for (const field of fields) {
    const value = fieldValue(field, raw[field.key]);
    if (value !== undefined) out[field.key] = value;
  }
  return out;
}

/** The console's port, in the container and on the host (compose maps 127.0.0.1 only). */
export const CONSOLE_PORT = 8081;

/** The kodra-agent.yaml content for a draft, as a plain object. */
export function draftToConfig(draft: AgentDraft): Record<string, unknown> {
  const provider = getModelProvider(draft.model.provider);
  const model: Record<string, unknown> = {
    provider: draft.model.provider,
    name: draft.model.name.trim(),
    ...fieldsObject(provider?.configFields ?? [], draft.model.fields),
  };
  for (const secret of provider?.secrets ?? []) model[secret.key] = secretRefFor(secret);

  const connectorsOut: Record<string, unknown> = {};
  for (const manifest of enabledConnectors(draft)) {
    const entry = draft.connectors[manifest.id];
    if (!entry) continue;
    const out: Record<string, unknown> = { enabled: true };
    if (manifest.accessLevels.length > 0) out['access'] = entry.access;
    const config = fieldsObject(manifest.configFields, entry.config);
    if (Object.keys(config).length > 0) out['config'] = config;
    const secrets = includedSecrets(manifest, entry.optionalSecrets, draft.target);
    if (secrets.length > 0) {
      out['secrets'] = Object.fromEntries(secrets.map((s) => [s.key, secretRefFor(s)]));
    }
    connectorsOut[manifest.id] = out;
  }

  const expires = draft.policy.expiresAfterMinutes.trim();
  return {
    apiVersion: SCHEMA_API_VERSION,
    kind: 'Agent',
    metadata: { name: draft.name.trim() },
    spec: {
      target: draft.target,
      model,
      connectors: connectorsOut,
      policy: {
        approvals: {
          required: true,
          approvers: splitList(draft.policy.approvers),
          expiresAfterMinutes: /^\d+$/.test(expires) ? Number(expires) : expires,
        },
        destructiveActions: draft.policy.destructiveActions,
      },
      audit: { path: DEFAULT_AUDIT_PATH },
      telemetry: { enabled: false },
      console: { enabled: draft.console.enabled, port: CONSOLE_PORT },
    },
  };
}

export function configYaml(draft: AgentDraft): string {
  const header = [
    '# Kodra AI Agent configuration, generated by the configurator.',
    '# Secret values never go in this file, only references to where they live.',
    '# yaml-language-server: $schema=https://raw.githubusercontent.com/kodra-io/kodra-agent/main/schema/kodra-agent.schema.json',
  ].join('\n');
  return `${header}\n${stringify(draftToConfig(draft), { lineWidth: 0 })}`;
}

function isHttpUrl(value: string): boolean {
  try {
    return ['http:', 'https:'].includes(new URL(value).protocol);
  } catch {
    return false;
  }
}

function validateField(field: ConfigField, raw: string | undefined, id: string, step: StepId) {
  const value = (raw ?? '').trim();
  const hasDefault = 'default' in field && field.default !== undefined;
  if (value === '') {
    return field.required && !hasDefault ? [{ field: id, step, code: 'required' as const }] : [];
  }
  switch (field.kind) {
    case 'url': {
      return isHttpUrl(value) ? [] : [{ field: id, step, code: 'url' as const }];
    }
    case 'string': {
      const ok = !field.pattern || new RegExp(field.pattern).test(value);
      return ok ? [] : [{ field: id, step, code: 'pattern' as const, hint: field.patternHint }];
    }
    case 'string-list': {
      const items = splitList(value);
      const ok = !field.pattern || items.every((i) => new RegExp(field.pattern ?? '').test(i));
      return ok ? [] : [{ field: id, step, code: 'pattern' as const, hint: field.patternHint }];
    }
    case 'integer': {
      const n = Number(value);
      const ok = /^\d+$/.test(value) && n >= field.min && n <= field.max;
      return ok
        ? []
        : [{ field: id, step, code: 'integer-range' as const, min: field.min, max: field.max }];
    }
  }
}

/**
 * Every problem that blocks the download, keyed to UI fields. The generated YAML is also run
 * through the real schema, so anything the field checks miss still blocks the download.
 */
export function validateDraft(draft: AgentDraft): DraftIssue[] {
  const issues: DraftIssue[] = [];
  const name = draft.name.trim();
  if (name === '') issues.push({ field: 'name', step: 'start', code: 'required' });
  else if (!NAME.test(name)) issues.push({ field: 'name', step: 'start', code: 'name-format' });

  if (draft.model.name.trim() === '') {
    issues.push({ field: 'model.name', step: 'model', code: 'required' });
  }
  for (const field of getModelProvider(draft.model.provider)?.configFields ?? []) {
    issues.push(
      ...validateField(field, draft.model.fields[field.key], `model.${field.key}`, 'model'),
    );
  }

  const enabled = enabledConnectors(draft);
  for (const manifest of enabled) {
    if (manifest.status === 'coming-soon') {
      issues.push({ field: `connector.${manifest.id}`, step: 'connectors', code: 'coming-soon' });
    }
    const entry = draft.connectors[manifest.id];
    for (const field of manifest.configFields) {
      issues.push(
        ...validateField(
          field,
          entry?.config[field.key],
          `connector.${manifest.id}.${field.key}`,
          'connectors',
        ),
      );
    }
  }
  for (const dep of dependencyIssues(enabled.map((m) => m.id))) {
    issues.push({
      field: `connector.${dep.connector}`,
      step: 'connectors',
      code: 'dependency',
      message: dep.message,
    });
  }

  const approvers = splitList(draft.policy.approvers);
  if (approvers.length === 0) {
    issues.push({ field: 'policy.approvers', step: 'review', code: 'required' });
  }
  for (const value of approvers.filter((a) => !APPROVER.test(a))) {
    issues.push({ field: 'policy.approvers', step: 'review', code: 'approver-format', value });
  }
  const expires = draft.policy.expiresAfterMinutes.trim();
  if (!/^\d+$/.test(expires) || Number(expires) < 1 || Number(expires) > 1440) {
    issues.push({
      field: 'policy.expiresAfterMinutes',
      step: 'review',
      code: 'integer-range',
      min: 1,
      max: 1440,
    });
  }

  if (issues.length === 0) {
    const result = parseAgentConfig(configYaml(draft));
    if (!result.ok) {
      for (const issue of result.issues) {
        issues.push({
          field: 'schema',
          step: 'review',
          code: 'schema',
          message: `${issue.path}: ${issue.message}`,
        });
      }
    }
  }
  return issues;
}
