apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kodra-agent.fullname" . }}
  labels:
    {{- include "kodra-agent.labels" . | nindent 4 }}
data:
  kodra-agent.yaml: |-
    {{- required "Pass the agent config: --set-file config=kodra-agent.yaml" .Values.config | nindent 4 }}
